### ISSUE TITLE
Python on Windows adding Window EOL

### ISSUE THREAD

**Issue by klovatt** [NotVaryClever/tomato-nvram#1]
Hi,

I have used this tool a number of times, and find it very useful. Thanks for taking the time to create this!

I recently decided to run this from my windows machine for a number of reasons and found that the set-nvram.sh scripts were unnusable due to the EOL characters.

I played around a bit and found a simple change to your code gets rid of the problem.

Simple change line 404 from:
        with open(args.output, 'w') as outfile:
to:
        with open(args.output, 'w', newline='\n') as outfile:

I don;t know if you wish to make this change in your official version, but it worked for me.

Thanks again!

Keith.

**Comment by NotVaryClever** [comment]
Oh that makes sense. I should change it to _always_ output linux line endings, even on windows, as you suggest.

Thank you and sorry for such a delayed reply!

**Comment by NotVaryClever** [comment]
I can see two use cases on Windows:

- Open `set-nvram.sh` in a Windows editor and copy-and-paste lines into another Windows program.
- Transfer `set-nvram.sh` to the router/Linux and edit/execute.

I think I should maintain the current behavior and **add a new `--linux` option** for outputting linux line endings on Windows.

**Comment by klovatt** [comment]
That sounds like a very good compromise.

Thanks!
