### ISSUE TITLE
Should have instruction for how to use the generated output file (set-nvram.sh)

### ISSUE THREAD

**Issue by ordtrogen** [NotVaryClever/tomato-nvram#4]
Last line of the "Use" (should it be "Usage"?) section says

>   View/Edit output set-nvam.sh to choose which settings to reapply.

but there is no information about what should be done with the output file. I'm guessing it should be uploaded to some directory on the router file system and then you should open a shell console on the router and execute the file. It would be nice if the readme.md had at least an outline of what steps to take.

Also, since this script is likely to be use in connection with a firmware upgrade of the router, maybe that (optional) step could be included in the instructions.

**Comment by mikey32230** [comment]
The ReadMe.md now specifies with examples of how to use the set-nvram.sh file. 
This issue should probably be marked as closed.

https://github.com/NotVaryClever/tomato-nvram#use

>Reapply settings over SSH:
> "C:\Program Files\PuTTY\plink.exe" -ssh root@192.168.1.1 -pw admin -m set-nvram.sh
Or
>$ ssh root@192.168.1.1 'sh -s' < set-nvram.sh

**Comment by ordtrogen** [comment]
Oh, you can do it in one go on the command line? Nice!
